# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:year/:month/:day/:title
exclude: ["node_modules", "vendor"]
sass:
  style: compressed

# Site info
url: http://danielstrunk.me/
title: Daniel Strunk web development and design

# Analytics
analytics:
  hostname: danielstrunk.me
  id: "UA-38448310-3"

# Collections
collections:
	work:
		output: true
		permalink: /work/:title

# Default variables
defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
      author: Daniel Strunk
