# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /til/:year/:title/
paginate: 5
paginate_path: /til/page/:num/
exclude: ["node_modules", "vendor"]
sass:
  style: compressed

# Site info
url: http://danielstrunk.me
title: Daniel Strunk

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# gems
gems:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# GitHub
repository: dstrunk/dstrunk.github.io
