# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /blog/:year/:month/:day/:title/
paginate: 8
paginate_path: /blog/page/:num/
exclude: ["node_modules", "vendor"]
sass:
  style: compressed

# Site info
url: http://danielstrunk.me
title: Daniel Strunk web development and design

# Collections
collections:
  work:
    output: true
    permalink: /work/:title/
  reference:
    output: true
    permalink: /reference/:title/

# Default variables
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      tags: []
      author: "Daniel Strunk"
      custom_js: [disqus.js]

# gems
gems:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# GitHub
repository: dstrunk/dstrunk.github.io
